on: [push, pull_request]
name: Test
jobs: 
  test:
    runs-on: ubuntu-latest
    container: golang:1.16beta1-alpine3.12
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...